// Code generated by "stringer -type CommandType"; DO NOT EDIT.

package unp

import "strconv"

const _CommandType_name = "C_POLLC_SREQC_AREQC_SRSPC_RES0C_RES1C_RES2C_RES3"

var _CommandType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42, 48}

func (i CommandType) String() string {
	if i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
