// Code generated by "stringer -type Subsystem"; DO NOT EDIT.

package unp

import "strconv"

const _Subsystem_name = "S_RES0S_SYSS_MACS_NWKS_AFS_ZDOS_SAPIS_UTILS_DBGS_APPS_OTAS_ZNPS_SPARE_12S_UBLS_RES14S_APP_CNFS_RES16S_PROTOBUFS_RES18S_RES19S_RES20S_GPS_MAX"

var _Subsystem_index = [...]uint8{0, 6, 11, 16, 21, 25, 30, 36, 42, 47, 52, 57, 62, 72, 77, 84, 93, 100, 110, 117, 124, 131, 135, 140}

func (i Subsystem) String() string {
	if i >= Subsystem(len(_Subsystem_index)-1) {
		return "Subsystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subsystem_name[_Subsystem_index[i]:_Subsystem_index[i+1]]
}
